version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: 'istrupin/multi-nginx'
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
      - redis
    image: 'istrupin/multi-server'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    depends_on:
      - api
    image: 'istrupin/multi-client'
  worker:
    depends_on:
      - redis
    image: 'istrupin/multi-worker'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379