#!/bin/bash
docker build -t istrupin/docker-ci .
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push istrupin/multi-client
docker push istrupin/multi-nginx
docker push istrupin/multi-server
docker push istrupin/multi-worker
